### ISSUE TITLE
EPIC helm chart self-hosted deployment support

### ISSUE THREAD

**Issue by tiina303** [PostHog/charts-clickhouse#129]
Tracking so we would know what users are struggling with. Please feel free to update/add

### Install failed

- [x] cluster too small - we have cluster requirements now on all pages ( https://posthogusers.slack.com/archives/C01GLBKHKQT/p1632033205050900 (too small cluster) &  https://github.com/PostHog/charts-clickhouse/issues/59 (too small cluster))
- [x] https://posthogusers.slack.com/archives/G01H7LGR7D0/p1629390081015800 (postgres helm repo, aws changing their docs underneath us)
- [x] https://posthogusers.slack.com/archives/CT7HXDEG3/p1631604962126200 (k8s 1.22 support, which is DONE now) 
- [x] Reinstall  (https://posthogusers.slack.com/archives/C01FKPGG5U6/p1631774038046900 (reinstall needs upgrade oddness & https://posthogusers.slack.com/archives/CT7HXDEG3/p1633603105399900 (2nd attempt, chi-clickhouse not coming up - upgrade fixes)

### uninstall
- [x] https://posthogusers.slack.com/archives/C02E48PCE0K/p1631625238004000 (namespace deletion finalizers) => https://github.com/PostHog/charts-clickhouse/issues/172

### Upgrade failed
- [x] https://github.com/PostHog/posthog/issues/6025 (migrate job to delete + re-run upgrade)

### TLS setup issues:
* https://posthogusers.slack.com/archives/CT7HXDEG3/p1631975228176900 (confusion around what hostname should be in aws)
* https://posthogusers.slack.com/archives/C01FKPGG5U6/p1631601029037600 (404s: 2 separate; maybe not tls for 2nd)
* https://posthogusers.slack.com/archives/G01JXEDAL22/p1632726015182800 (???)
* https://github.com/PostHog/charts-clickhouse/issues/133

### Something broke in prod:
- [x] https://posthog.slack.com/archives/C021HLFPAA2/p1631220219019900 (plug-in server couldn't connect to Redis; restart helped) => /health endpoint issue

### Kafka:
- [x] https://posthogusers.slack.com/archives/CT7HXDEG3/p1632561949288200 (kafka out of space & resizing didn't work as expected) & https://posthogusers.slack.com/archives/C01FKPGG5U6/p1632577233112700 + issues in comments => we have kafka runbook docs now + changing default sizes atm

### Other:
- [x] dry-run crds missing failure - expected https://github.com/PostHog/charts-clickhouse/issues/91
- [x] Lookup usage / increase disk size: https://posthogusers.slack.com/archives/CT7HXDEG3/p1632290353227900

**Comment by macobo** [comment]
Kafka resizing/configuration is a p0 thing IMO - seems like a lot of installations run into this, including ourselves

Slack threads:
- https://posthogusers.slack.com/archives/G01JXEDAL22/p1632708757181700
- https://posthogusers.slack.com/archives/CT7HXDEG3/p1632336279240900
- https://posthogusers.slack.com/archives/C026SNNE430/p1628192801014300
- https://github.com/PostHog/product-internal/issues/54

**Comment by macobo** [comment]
Another slack issue: https://app.slack.com/client/TT68H7WHY/CT7HXDEG3/thread/CT7HXDEG3-1632993135.320100

**Comment by tiina303** [comment]
Updated the description, now just the TLS problems that have been a recurring theme in support questions & @guidoiaquinti has been looking into cert manager already on the chart side
